# Copyright (c) 2012-2017 Red Hat, Inc
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Release.Namespace -}} -keycloak-role-binding
roleRef:
  kind: Role
  name: che-endpoints-monitor
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: che-keycloak
  namespace: {{ .Release.Namespace }}
